### PR TITLE
Afraupdate

### PR DESCRIPTION
**Pull request by AfraAljarwan**
Guys here are my folders for now can you check them : )

### CODE REVIEW

**Review by RanimHilal — COMMENTED** [review]
Everything is good but edit your css links

**Comment by AfraAljarwan** [comment]
> Everything is good but edit your css links

I edit it now you can check it

**Comment by RanimHilal** [comment]
> > Everything is good but edit your css links
> 
> I edit it now you can check it

Thank you

**Review by RanimHilal — APPROVED** [review]

**Review by Shamsa900 — APPROVED** [review]
Yes now it's good

**Pull request merged**
