### PR TITLE
afra_js

### PR DESCRIPTION
**Pull request by AfraAljarwan**
Guys I did my login javascript page the idea is by clicking on submit button it pop up a message to the user to show if he must fill out or they are successfully logged in but the main problem is that the code works in jsfiddle and when I save it in my folders the message is not appearing.

### CODE REVIEW

**Review by fatmalshamsi — COMMENTED** [review]
im dealing with the same issue here but great idea nonetheless

**Comment by Shamsa900** [comment]
the idea is great, and it represent the idea of the interaction between the user and the website.

Check the programming maybe when you copy it there is something missing or try to use an online css, html compiler.

**Comment by Shamsa900** [comment]
or try to check validation of your code on the website that we always use.

**Comment by Hajar-Abdullah** [comment]
Great idea Afra!
Try to check the links spelling or use another text editor.

**Comment by AfraAljarwan** [comment]
> or try to check validation of your code on the website that we always use.

Thanks, I will check the code now.

**Comment by AfraAljarwan** [comment]
I checked the spelling its correct and for the code it doesn't have an error :(

**Comment by AfraAljarwan** [comment]
Thanks guys I figured it out.

**Comment by AfraAljarwan** [comment]
There was a problem with javascript link.

**Pull request merged**
