### PR TITLE
new addition, Mockup + HTML files + CSS files

### PR DESCRIPTION
**Pull request by Hajar-Abdullah**
Kindly guys review and check my files.

### CODE REVIEW

**Comment by AfraAljarwan** [comment]
Everything is perfect but edit your css link

**Comment by AfraAljarwan** [comment]
href="_____ Rating_Page.css">
Here you should add the github link so it link the html with css

**Review by fatmalshamsi — COMMENTED** [review]
i have a question about the ratings,, does the picture of the rating changes when a certain option is selected?  if not i think its going to be a great addition maybe we can try adding it using javascript !!

**Comment by Hajar-Abdullah** [comment]
> href="_____ Rating_Page.css"> Here you should add the github link so it link the html with css

Thank you Afra, I will edit it right now.

**Comment by Hajar-Abdullah** [comment]
> i have a question about the ratings,, does the picture of the rating changes when a certain option is selected? if not i think its going to be a great addition maybe we can try adding it using javascript !!

Regarding your question, No the picture of the rating doesn't change when the user select an option.  
Great idea Fatima, thank you so much. I will try to apply this idea in javascript phase by using control statements.

**Review by RanimHilal — CHANGES_REQUESTED** [review]
I apologize for replying late but in the links change "Homepage" to "html" bc we changed the files.
Also can you remove the html files from css folder?

**Comment by Hajar-Abdullah** [comment]
> I apologize for replying late but in the links change "Homepage" to "html" bc we changed the files. Also can you remove the html files from css folder?

No need to apologize Ranim, Thank you so much.
I will edit it right now.

**Review by RanimHilal — APPROVED** [review]

**Review by fatmalshamsi — APPROVED** [review]

**Pull request merged**
