### PR TITLE
shamsa update

### PR DESCRIPTION
**Pull request by Shamsa900**
Hello can you see my update ?

### CODE REVIEW

**Review by RanimHilal — COMMENTED** [review]
Please edit your css links and the books links. If you want help with the links tell us.

**Comment by fatmalshamsi** [comment]
Yes we can see it

**Comment by Hajar-Abdullah** [comment]
Yes we can see your updates.

**Review by fatmalshamsi — COMMENTED** [review]
what is  contenteditable="true" spellcheck="false" in the booktok html page

**Review by RanimHilal — APPROVED** [review]

**Review by Hajar-Abdullah — APPROVED** [review]

**Review by AfraAljarwan — APPROVED** [review]

**Pull request merged**
