### PR TITLE
Js branch

### PR DESCRIPTION
**Pull request by fatmalshamsi**
Hey guys this is my idea for the javascrpit on the friends page, the user will press on the button "ADD FRIEND" and a prompt will appear asking to type the username, after pressing enter a message will appear that the user has been added.

### CODE REVIEW

**Comment by Shamsa900** [comment]
It's great idea fatima

for my part I will be adding a curser for the About Us page which is a black circle but when you hover over the text it become white I mean the text.

**Comment by Shamsa900** [comment]
What do you think about the two ideas ??

**Comment by RanimHilal** [comment]
actually, both ideas are good both of them interact with the users.
I also want to use javascript in my pages because it turns out I can't move between the images I added with only css. I will show you what I did when I edit it

**Comment by AfraAljarwan** [comment]
Great ideas guys.

**Comment by AfraAljarwan** [comment]
Using JavaScript allows you to interact with user and make your pages more interactive.

**Comment by fatmalshamsi** [comment]
> 

great thank you i like your idea too we can use both

**Comment by RanimHilal** [comment]
this is not about js but I have a css for books but I feel it will be confusing and tiring to copy it in every link. is it alright to keep it in one book or should I add it to all thebooks? it is only additional info

**Comment by fatmalshamsi** [comment]
> this is not about js but I have a css for books but I feel it will be confusing and tiring to copy it in every link. is it alright to keep it in one book or should I add it to all thebooks? it is only additional info

hello raneem its just linking it to an external css right? we will help if u need any so if you would like tell me which books to work with and i will help you.

**Comment by RanimHilal** [comment]
> this is not about js but I have a css for books but I feel it will be confusing and tiring to copy it in every link. is it alright to keep it in one book or should I add it to all the books? it is only additional info

also if anyone has a javascript and wants to merge it tell me so that I close this pull request and open another for meging then I will reopen this to continue discussing

**Comment by Hajar-Abdullah** [comment]
I like your ideas guys. Great job!
Your ideas make the web page dynamic and interactive, and it create a kind of communication between the users.

**Comment by RanimHilal** [comment]
> > this is not about js but I have a css for books but I feel it will be confusing and tiring to copy it in every link. is it alright to keep it in one book or should I add it to all thebooks? it is only additional info
> 
> hello raneem its just linking it to an external css right? we will help if u need any so if you would like tell me which books to work with and i will help you.

not only linking but also copying part of some html. I'm thinking of only adding it to the books that are shown in homepage(but still need help) do u think it is better?

**Comment by fatmalshamsi** [comment]
> > > this is not about js but I have a css for books but I feel it will be confusing and tiring to copy it in every link. is it alright to keep it in one book or should I add it to all thebooks? it is only additional info
> > 
> > 
> > hello raneem its just linking it to an external css right? we will help if u need any so if you would like tell me which books to work with and i will help you.
> 
> not only linking but also copying part of some html. I'm thinking of only adding it to the books that are shown in homepage(but still need help) do u think it is better?

will do what we can with it mainly doing the homeoage books the rest if we have time we will try.

**Review by RanimHilal — APPROVED** [review]

**Pull request merged**
